### ISSUE TITLE
Gizmo works poorly when the camera is far.

### ISSUE THREAD

**Issue by BigPhilCombo** [ssatguru/BabylonJS-EditControl.java#5]
If your camera is far away from the object your are trying to manipulate, the controls become extremely inconsistent.

For example if you modify your sample scene so that your ArcCamera has a much larger radius, you will notice the controls are almost unusable.

```javascript
camera = new BABYLON.ArcRotateCamera("ArcRotateCamera", 1, 1.2,	2000, new BABYLON.Vector3(0, 0, 0), scene);
```

**Comment by ssatguru** [comment]
you are right.
the control uses a pick plane to sense mouse movement size.
currently it is fixed size.
I probably need to scale it with radius.
will work on it

**Comment by ssatguru** [comment]
fixed in the typescript version 
[https://github.com/ssatguru/EditControl.ts](https://github.com/ssatguru/EditControl.ts)
